=== LZTT/schema/data/schedule.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- data types -->
<!-- time data -->
    <xs:simpleType name="Stime">
        <xs:restriction base="xs:integer">
            <xs:pattern value="[0-2][0-9][0-5][0-9]" />
        </xs:restriction>
    </xs:simpleType>  
      
<!-- course data -->
    <xs:simpleType name="Scourse">
        <xs:restriction base="xs:string">
            <xs:pattern value="ACIT[1-4][0-9][0-9][0-9]"/>
        </xs:restriction>
    </xs:simpleType>
    
<!-- day of week -->
    <xs:simpleType name="Sday">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Monday"/>
            <xs:enumeration value="Tuesday"/>
            <xs:enumeration value="Wednesday"/>
            <xs:enumeration value="Thursday"/>
            <xs:enumeration value="Friday"/>
        </xs:restriction>
    </xs:simpleType>
        
<!-- instructor data -->        
        <xs:simpleType name="Sins">
            <xs:restriction base="xs:string"/>
        </xs:simpleType>   
<!-- room data --> 
        <xs:simpleType name="Sroom">
            <xs:restriction base="xs:string"/>
        </xs:simpleType>
<!-- type data --> 
        <xs:simpleType name="Stype">
            <xs:restriction base="xs:string"/>
        </xs:simpleType>
<!-- duration data--> 
        <xs:simpleType name="Sdur">
            <xs:restriction base="xs:integer">
                <xs:pattern value="[0-2]" />
            </xs:restriction>
        </xs:simpleType>

<!-- a schedule contains a bunch of origin elements -->
    <xs:element name="schedule">
        <xs:complexType>
                <xs:sequence>
                    <xs:element name="by_day" type="Sbyday" maxOccurs="1"/>
                    <xs:element name="by_time" type="Sbytime" maxOccurs="1"/>
                    <xs:element name="by_course" type="Sbycourse" maxOccurs="1"/>
                </xs:sequence>
            </xs:complexType>
    </xs:element>

  <!-- for day facet -->
        <xs:complexType name="Sbyday">
            <xs:sequence>
                <xs:element name="book_day" type="Sbday" maxOccurs="5"/>
            </xs:sequence>
        </xs:complexType>
            
        <xs:complexType name="Sbday">
            <xs:sequence>
                <xs:element name="class_time" type="Sctime" maxOccurs="5"/>
            </xs:sequence>
            <xs:attribute name="day" type="Sday" use="required" />
        </xs:complexType>
        
        <xs:complexType name="Sctime">
            <xs:sequence>
                <xs:element name="the_course" type="Sdcourse" maxOccurs="1"/>
                <xs:element name="detail" type="Sddetail" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="time" type="Stime" use="required" />
        </xs:complexType>
        
        <xs:complexType name="Sdcourse">
            <xs:attribute name="number" type="Scourse" use="required" />
        </xs:complexType>
        
        <xs:complexType name="Sddetail">
            <xs:attribute name="instructor" type="Sins" use="required" />
            <xs:attribute name="room" type="Sroom" use="optional" />
            <xs:attribute name="type" type="Stype" use="required" />
            <xs:attribute name="dur" type="Sdur" use="required" />
        </xs:complexType>
        

<!-- for time facet -->
        <xs:complexType name="Sbytime">
            <xs:sequence>
                <xs:element name="book_time" type="Sbtime" maxOccurs="5"/>
            </xs:sequence>
        </xs:complexType>
            
        <xs:complexType name="Sbtime">
            <xs:sequence>
                <xs:element name="week_day" type="Swday" maxOccurs="5"/>
            </xs:sequence>
            <xs:attribute name="time" type="Stime" use="required" />
        </xs:complexType>
        
        <xs:complexType name="Swday">
            <xs:sequence>
                <xs:element name="course" type="Stcourse" maxOccurs="1"/>
                <xs:element name="detail" type="Stdetail" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="day" type="Sday" use="required" />
        </xs:complexType>
        
        <xs:complexType name="Stcourse">
            <xs:attribute name="number" type="Scourse" use="required" />
        </xs:complexType>
        
        <xs:complexType name="Stdetail">
            <xs:attribute name="instructor" type="Sins" use="required" />
            <xs:attribute name="room" type="Sroom" use="optional" />
            <xs:attribute name="type" type="Stype" use="required" />
            <xs:attribute name="dur" type="Sdur" use="required" />
        </xs:complexType>

<!-- for course facet -->
        <xs:complexType name="Sbycourse">
            <xs:sequence>
                <xs:element name="book_course" type="Sbcourse" maxOccurs="5"/>
            </xs:sequence>
        </xs:complexType>
            
        <xs:complexType name="Sbcourse">
            <xs:sequence>
                <xs:element name="this_week" type="Stday" maxOccurs="5"/>
            </xs:sequence>
            <xs:attribute name="number" type="Scourse" use="required" />
        </xs:complexType>
        
        <xs:complexType name="Stday">
            <xs:sequence>
                <xs:element name="blocks" type="Scblocks" maxOccurs="1"/>
                <xs:element name="detail" type="Scdetail" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="day" type="Sday" use="required" />
        </xs:complexType>
        
        <xs:complexType name="Scblocks">
            <xs:attribute name="time" type="Stime" use="required" />
        </xs:complexType>
        
        <xs:complexType name="Scdetail">
            <xs:attribute name="instructor" type="Sins" use="required" />
            <xs:attribute name="room" type="Sroom" use="optional" />
            <xs:attribute name="type" type="Stype" use="required" />
            <xs:attribute name="dur" type="Sdur" use="required" />
        </xs:complexType>

</xs:schema>

=== LZTT/schema/data/scheduleSD.xml
<?xml version="1.0"?>
<?xml-stylesheet type='text/xsl' href='scheduleSD.xsl'?>


<schedule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="schedule.xsd">
  <by_day> 
        <book_day day="Monday" >
            <class_time time="0930">
                <the_course number="ACIT4850" />
                <detail instructor="Jim" room="SW3-1750" type="" dur="2"/>
            </class_time>
        </book_day>
        <book_day day="Tuesday" >
            <class_time time="1130">
                <the_course number="ACIT4850" />
                <detail instructor="Jim" room="SW3-1750" type="" dur="2"/>
            </class_time>
        </book_day>
        <book_day day="Wednesday" >
            <class_time time="1230">
                <the_course number="ACIT4850" />
                <detail instructor="Jim" room="SW3-1750" type="" dur="2"/>
            </class_time>
        </book_day>
         <book_day day="Friday" >
            <class_time time="1430">
                <the_course number="ACIT4850" />
                <detail instructor="Jim" room="SW3-1750" type="" dur="2"/>
            </class_time>
        </book_day>
    </by_day>
    <by_time>
        <book_time time="0830">
            <week_day day="Tuesday">
                <course number="ACIT4620" />
                <detail instructor="Bethany" room="SE12-306" type="" dur="2"/>
            </week_day>
            <week_day day="Friday">
                <course number="ACIT4660" />
                <detail instructor="Steve" room="SW9-206" type="" dur="2"/>
            </week_day>
        </book_time>
        <book_time time="1530">
            <week_day day="Monday">
                <course number="ACIT4620" />
                <detail instructor="Bethany" room="SE12-306" type="" dur="2"/>
            </week_day>
            <week_day day="Wednesday">
                <course number="ACIT4660" />
                <detail instructor="Steve" room="SW9-206" type="" dur="2"/>
            </week_day>
        </book_time>
    </by_time>
    <by_course>
        <book_course number="ACIT4910">
            <this_week day="Monday">
                <blocks time="1530" />
                <detail instructor="Richard" room="SW9-206" type="" dur="1"/>
            </this_week>
            <this_week day="Thursday">
                <blocks time="0930" />
                <detail instructor="Richard" room="SW5-1840" type="" dur="1"/>
            </this_week>
            <this_week day="Thursday">
                <blocks time="1030" />
                <detail instructor="Richard" room="SE12-306" type="" dur="2"/>
            </this_week>
        </book_course>
    </by_course>
</schedule>
